### ISSUE TITLE
代码结果不收敛

### ISSUE THREAD

**Issue by A-new-b** [xiaohuiduan/dcgan_anime_avatars#1]
个人在实机上和kaggle上都跑了一边，您的代码返回的图片
![图片](https://user-images.githubusercontent.com/43344034/103517466-21e69380-4ead-11eb-836a-4e7a10bd1e09.png)
大部分都与这类似，结果似乎并不收敛
同时您的博客上的代码 train(epochs=500, batch_size=32)，似乎是打错了
但个人只是个小白，看不出问题的所在

**Comment by chenjie-dev** [comment]
我也是，colab上跑了一次，代码结结果没有收敛。

**Comment by chenjie-dev** [comment]
![image](https://user-images.githubusercontent.com/39252298/118401892-12b4f500-b69a-11eb-90b2-c7d0c5b9404c.png)

**Comment by xiaohuiduan** [comment]
很抱歉，github这边的comment没有邮件通知，导致我现在才看到你们的Issue。我接下来会找个时间去看一看是怎么回事 @CJ112211 @A-new-b

**Comment by xiaohuiduan** [comment]
@CJ112211 @A-new-b  代码已更新，结果可以收敛。大概10轮就可以查看到结果

**Comment by xiaohuiduan** [comment]
代码已更新，具体查看https://www.cnblogs.com/xiaohuiduan/p/13274675.html 
代码运行10个epoch可以看到结果

![100个epoch](https://user-images.githubusercontent.com/40485068/130042939-c9bce2e5-6dbf-4efd-b4a1-197683b7308b.png)
